// CineStream — Movie & TV Data
// Replace poster URLs with real TMDB image URLs in production
// Format: https://image.tmdb.org/t/p/w500{poster_path}

const MOVIES = [
  // HERO FEATURED
  { id:1, title:"Dune: Part Two", year:2024, rating:8.6, duration:"2h 46m", genre:"sci-fi", type:"movie",
    desc:"Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against those who destroyed his family.",
    poster:"https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    director:"Denis Villeneuve", cast:"Timothée Chalamet, Zendaya, Rebecca Ferguson",
    tags:["HD","Featured","New"] },
  { id:2, title:"Oppenheimer", year:2023, rating:8.9, duration:"3h 0m", genre:"drama", type:"movie",
    desc:"The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    poster:"https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
    director:"Christopher Nolan", cast:"Cillian Murphy, Emily Blunt, Robert Downey Jr.",
    tags:["HD","Top Rated"] },
  { id:3, title:"Killers of the Flower Moon", year:2023, rating:7.7, duration:"3h 26m", genre:"drama", type:"movie",
    desc:"Members of the Osage Nation are murdered under mysterious circumstances in 1920s Oklahoma.",
    poster:"https://image.tmdb.org/t/p/w500/dB6Krk806zeqd0YoiQztffQMNhq.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/1X7vow16X7CnCoexXh4H4F2yDJv.jpg",
    director:"Martin Scorsese", cast:"Leonardo DiCaprio, Robert De Niro, Lily Gladstone",
    tags:["HD"] },
  { id:4, title:"Poor Things", year:2023, rating:8.1, duration:"2h 21m", genre:"comedy", type:"movie",
    desc:"The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by an eccentric scientist.",
    poster:"https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXYmHe6At3jdGEL.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/4woSOUD0equyobgFBDI32e4BURA.jpg",
    director:"Yorgos Lanthimos", cast:"Emma Stone, Mark Ruffalo, Willem Dafoe",
    tags:["HD","Award Winner"] },
  { id:5, title:"The Zone of Interest", year:2023, rating:7.4, duration:"1h 45m", genre:"drama", type:"movie",
    desc:"A Holocaust drama set in the present day, following Auschwitz commandant Rudolf Höss and his family.",
    poster:"https://image.tmdb.org/t/p/w500/hUu9zyZmKuTKqiAoOQFEFHlQDvU.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/sOwBiQRDASGhUlD2twtPiAlKqGe.jpg",
    director:"Jonathan Glazer", cast:"Christian Friedel, Sandra Hüller",
    tags:["HD"] },

  // TRENDING
  { id:6, title:"Deadpool & Wolverine", year:2024, rating:7.9, duration:"2h 7m", genre:"action", type:"movie",
    desc:"Deadpool is recruited by the Time Variance Authority to go on a mission with an unwilling Wolverine.",
    poster:"https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    director:"Shawn Levy", cast:"Ryan Reynolds, Hugh Jackman, Emma Corrin",
    tags:["HD","New","Trending"] },
  { id:7, title:"Inside Out 2", year:2024, rating:7.8, duration:"1h 40m", genre:"animation", type:"movie",
    desc:"Riley enters puberty and a new emotion — Anxiety — leads the pack of new emotions that arrive.",
    poster:"https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/see9BCecXDuLpX7WrVTiI3KPKD9.jpg",
    director:"Kelsey Mann", cast:"Amy Poehler, Maya Hawke, Kensington Tallman",
    tags:["HD","Trending"] },
  { id:8, title:"Alien: Romulus", year:2024, rating:7.4, duration:"1h 59m", genre:"horror", type:"movie",
    desc:"A group of teenagers on a space station make a terrifying discovery.",
    poster:"https://image.tmdb.org/t/p/w500/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
    director:"Fede Álvarez", cast:"Cailee Spaeny, David Jonsson, Archie Renaux",
    tags:["HD","New"] },
  { id:9, title:"Twisters", year:2024, rating:7.2, duration:"2h 2m", genre:"action", type:"movie",
    desc:"Kate Cooper is lured back to the open plains of Oklahoma by her friend Javi to test a new tornado-chasing system.",
    poster:"https://image.tmdb.org/t/p/w500/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
    director:"Lee Isaac Chung", cast:"Daisy Edgar-Jones, Glen Powell, Anthony Ramos",
    tags:["HD"] },
  { id:10, title:"Longlegs", year:2024, rating:6.2, duration:"1h 41m", genre:"thriller", type:"movie",
    desc:"FBI Agent Lee Harker is assigned to an unsolved serial killer case that takes a sinister turn.",
    poster:"https://image.tmdb.org/t/p/w500/jcEl8SISNfGdlQFjGjHkQaIX5t6.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/Ah1cOgj4sPTBp2bAQfJQF7YHBaP.jpg",
    director:"Osgood Perkins", cast:"Maika Monroe, Nicolas Cage, Blair Underwood",
    tags:["HD"] },

  // MORE MOVIES
  { id:11, title:"Godzilla x Kong: The New Empire", year:2024, rating:6.3, duration:"1h 55m", genre:"action", type:"movie",
    poster:"https://image.tmdb.org/t/p/w500/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/xRd1eJIDe7JHO5KAsFc5SxFBEWk.jpg",
    desc:"Godzilla and Kong must unite to face a colossal threat hidden in the world below.",
    director:"Adam Wingard", cast:"Rebecca Hall, Brian Tyree Henry, Dan Stevens",tags:["HD"] },
  { id:12, title:"The Fall Guy", year:2024, rating:7.0, duration:"2h 6m", genre:"action", type:"movie",
    poster:"https://image.tmdb.org/t/p/w500/aBPwlJJTUZBZLHhDQFdlSvQV1oa.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/H5HjE7Xb9N09rbWn1zBfxgI8uz.jpg",
    desc:"A stuntman is drawn back into action when the star of a film he's working on goes missing.",
    director:"David Leitch", cast:"Ryan Gosling, Emily Blunt, Aaron Taylor-Johnson",tags:["HD"] },
  { id:13, title:"Furiosa: A Mad Max Saga", year:2024, rating:7.7, duration:"2h 28m", genre:"action", type:"movie",
    poster:"https://image.tmdb.org/t/p/w500/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/cMkYXHJAFwkMK3lam0mfYKEBb73.jpg",
    desc:"As the world falls, a young Furiosa is snatched from the Green Place of Many Mothers.",
    director:"George Miller", cast:"Anya Taylor-Joy, Chris Hemsworth, Tom Burke",tags:["HD"] },
  { id:14, title:"Civil War", year:2024, rating:7.3, duration:"1h 49m", genre:"thriller", type:"movie",
    poster:"https://image.tmdb.org/t/p/w500/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/pjILkv5o4WgCHNOHOmN5KIoWKdy.jpg",
    desc:"A journey across a dystopian future America, following a team of military-embedded journalists.",
    director:"Alex Garland", cast:"Kirsten Dunst, Wagner Moura, Cailee Spaeny",tags:["HD"] },
  { id:15, title:"Kingdom of the Planet of the Apes", year:2024, rating:7.2, duration:"2h 25m", genre:"sci-fi", type:"movie",
    poster:"https://image.tmdb.org/t/p/w500/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/fqv8v6AycXKsivp1T5yKtLbGXce.jpg",
    desc:"Many years after the reign of Caesar, a young ape goes on a journey that leads him to question everything.",
    director:"Wes Ball", cast:"Owen Teague, Freya Allan, Kevin Durand",tags:["HD"] },
  { id:16, title:"Argylle", year:2024, rating:6.2, duration:"2h 19m", genre:"action", type:"movie",
    poster:"https://image.tmdb.org/t/p/w500/95ahIDMbBfmGCGgOEkCkMNnCrxT.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/uKb22E0xdCCuBGWRSEV4QdHCaWh.jpg",
    desc:"A reclusive spy novelist's fictional world begins to mirror real events.",
    director:"Matthew Vaughn", cast:"Bryce Dallas Howard, Henry Cavill, Sam Rockwell",tags:["HD"] },
  { id:17, title:"Wicked", year:2024, rating:7.8, duration:"2h 40m", genre:"romance", type:"movie",
    poster:"https://image.tmdb.org/t/p/w500/c5Tqxeo1UpBvnAc3csUm7j3hlQl.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/mHTjDAaRBm9f4dQJLQFOOxxV5Vc.jpg",
    desc:"The story of the unlikely friendship between Elphaba and Glinda in the land of Oz.",
    director:"Jon M. Chu", cast:"Cynthia Erivo, Ariana Grande, Jeff Goldblum",tags:["HD","New"] },
  { id:18, title:"Gladiator II", year:2024, rating:7.4, duration:"2h 28m", genre:"action", type:"movie",
    poster:"https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/euYIwmwkmz95mnXvCEKd1ahFanN.jpg",
    desc:"Years after witnessing the death of Maximus, Lucius must fight in the Colosseum.",
    director:"Ridley Scott", cast:"Paul Mescal, Denzel Washington, Pedro Pascal",tags:["HD","New"] },
  { id:19, title:"Moana 2", year:2024, rating:7.2, duration:"1h 40m", genre:"animation", type:"movie",
    poster:"https://image.tmdb.org/t/p/w500/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/b9cXPSoTFGaXcjeVT1MBVlsvpVP.jpg",
    desc:"Moana receives an unexpected call from her wayfinding ancestors.",
    director:"Dana Ledoux Miller", cast:"Auli'i Cravalho, Dwayne Johnson",tags:["HD","New"] },
  { id:20, title:"Conclave", year:2024, rating:7.9, duration:"2h 0m", genre:"thriller", type:"movie",
    poster:"https://image.tmdb.org/t/p/w500/m3X8P3nQLwMW5mEBVaQrEXv4bzR.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/3mFdRk3GePuFQqvgpQbJeVhQBLk.jpg",
    desc:"After the death of the Pope, a cardinal oversees one of the world's most secretive events — the election of a new Pope.",
    director:"Edward Berger", cast:"Ralph Fiennes, Stanley Tucci, John Lithgow",tags:["HD"] },

  // TOP RATED
  { id:21, title:"The Shawshank Redemption", year:1994, rating:9.3, duration:"2h 22m", genre:"drama", type:"movie",
    poster:"https://image.tmdb.org/t/p/w500/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    desc:"Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    director:"Frank Darabont", cast:"Tim Robbins, Morgan Freeman, Bob Gunton",tags:["HD","Classic"] },
  { id:22, title:"The Dark Knight", year:2008, rating:9.0, duration:"2h 32m", genre:"action", type:"movie",
    poster:"https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/nMKdUFX8pSZOH6HB6WtKuinGkMo.jpg",
    desc:"Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    director:"Christopher Nolan", cast:"Christian Bale, Heath Ledger, Aaron Eckhart",tags:["HD","Classic"] },
  { id:23, title:"Inception", year:2010, rating:8.8, duration:"2h 28m", genre:"sci-fi", type:"movie",
    poster:"https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    desc:"A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea.",
    director:"Christopher Nolan", cast:"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",tags:["HD","Classic"] },
  { id:24, title:"Interstellar", year:2014, rating:8.7, duration:"2h 49m", genre:"sci-fi", type:"movie",
    poster:"https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/pbrkL804c8yAv3zBZR4QPEafpAR.jpg",
    desc:"A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    director:"Christopher Nolan", cast:"Matthew McConaughey, Anne Hathaway, Jessica Chastain",tags:["HD","Classic"] },
  { id:25, title:"Pulp Fiction", year:1994, rating:8.9, duration:"2h 34m", genre:"crime", type:"movie",
    poster:"https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    desc:"The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    director:"Quentin Tarantino", cast:"John Travolta, Samuel L. Jackson, Uma Thurman",tags:["HD","Classic"] },
];

const SERIES = [
  { id:101, title:"House of the Dragon", year:2022, rating:8.4, duration:"60m / ep", genre:"drama", type:"series",
    poster:"https://image.tmdb.org/t/p/w500/1X4h40fcB4WWUmIBK0auT4zRBAV.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
    desc:"The story of House Targaryen set 200 years before the events of Game of Thrones.",
    director:"Miguel Sapochnik", cast:"Paddy Considine, Emma D'Arcy, Matt Smith",
    tags:["HD","Series","Trending"], seasons:2 },
  { id:102, title:"The Bear", year:2022, rating:8.7, duration:"30m / ep", genre:"drama", type:"series",
    poster:"https://image.tmdb.org/t/p/w500/sHFlbKS3WLqMnp9t2ghADIJFnuQ.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/qMw0JFMnAeVq3F7bvvqv4eaXR7p.jpg",
    desc:"A young chef from the fine dining world comes home to Chicago to run his family sandwich shop.",
    director:"Christopher Storer", cast:"Jeremy Allen White, Ebon Moss-Bachrach, Ayo Edebiri",
    tags:["HD","Series","Award Winner"], seasons:3 },
  { id:103, title:"Shogun", year:2024, rating:8.7, duration:"50m / ep", genre:"drama", type:"series",
    poster:"https://image.tmdb.org/t/p/w500/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/ifUfE79O1raUwbaQRIB7XnFz5ZC.jpg",
    desc:"Set in feudal Japan, an English navigator finds himself in the middle of a power struggle.",
    director:"Rachel Kondo", cast:"Hiroyuki Sanada, Cosmo Jarvis, Anna Sawai",
    tags:["HD","Series","New","Trending"], seasons:1 },
  { id:104, title:"The Last of Us", year:2023, rating:8.7, duration:"50m / ep", genre:"thriller", type:"series",
    poster:"https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/a3ZcS29XpG5b55n7zGFiqYqBjUx.jpg",
    desc:"Joel and Ellie must survive in a post-apocalyptic world overrun by a fungal infection.",
    director:"Craig Mazin", cast:"Pedro Pascal, Bella Ramsey, Gabriel Luna",
    tags:["HD","Series"], seasons:2 },
  { id:105, title:"Severance", year:2022, rating:8.7, duration:"50m / ep", genre:"thriller", type:"series",
    poster:"https://image.tmdb.org/t/p/w500/nAkXDl5PmGMqBSKR1elp5FVD2N5.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/fW1hRNSbFYIiUC3pDrQiTsqHGJH.jpg",
    desc:"A biotech company's employees surgically separate their work and personal memories.",
    director:"Ben Stiller", cast:"Adam Scott, Zach Cherry, Britt Lower",
    tags:["HD","Series"], seasons:2 },
  { id:106, title:"Fallout", year:2024, rating:8.5, duration:"60m / ep", genre:"sci-fi", type:"series",
    poster:"https://image.tmdb.org/t/p/w500/AnsSKSPBT3MKPZ2bRHNkCEXGXYD.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/4AoWx9SbFDLLmBZUMBjQXuHQNqt.jpg",
    desc:"200 years after the apocalypse, a Vault dweller ventures into the wasteland.",
    director:"Graham Wagner", cast:"Ella Purnell, Walton Goggins, Kyle MacLachlan",
    tags:["HD","Series","New","Trending"], seasons:1 },
  { id:107, title:"The Penguin", year:2024, rating:8.6, duration:"55m / ep", genre:"crime", type:"series",
    poster:"https://image.tmdb.org/t/p/w500/ikuvILkGgmWU98Csp8xmF3kLMrg.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/2uyobHXhpJFXLRkGBrWGLvCFrMb.jpg",
    desc:"After the death of Carmine Falcone, Oz Cobb seizes his chance to grab the Gotham criminal empire.",
    director:"Lauren LeFranc", cast:"Colin Farrell, Cristin Milioti, Rhenzy Feliz",
    tags:["HD","Series","New"], seasons:1 },
  { id:108, title:"Only Murders in the Building", year:2021, rating:8.1, duration:"35m / ep", genre:"comedy", type:"series",
    poster:"https://image.tmdb.org/t/p/w500/6jVSBHRubKqNIisWQWGKHqvgHHl.jpg",
    backdrop:"https://image.tmdb.org/t/p/w1280/7EvtCOANcbX5lVwJA1ZBrx9nEkk.jpg",
    desc:"Three strangers become obsessed with a true crime case in their New York apartment building.",
    director:"John Hoffman", cast:"Steve Martin, Martin Short, Selena Gomez",
    tags:["HD","Series"], seasons:4 },
];

const ALL_CONTENT = [...MOVIES, ...SERIES];
const HERO_ITEMS = MOVIES.slice(0, 5);
